export const studentRoutine = [
  // ***** MORNING *****
  {
    id: 1,
    task: "Wake up early",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg1.jpg?alt=media&token=d3cfed58-378d-4d15-afa8-2bc13d2f1093",
  },
  {
    id: 2,
    task: "Practice deep breathing or meditation",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg10.jpg?alt=media&token=df13fa1f-83be-4d57-9654-38a103361f71",
  },
  {
    id: 3,
    task: "Have a healthy breakfast",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg11.jpg?alt=media&token=736d6a5b-2a95-4504-b013-7c1581dce281",
  },
  {
    id: 4,
    task: "Spend some time in nature",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg25.jpg?alt=media&token=1f1c02a9-41e0-4c6c-9497-2e1cdf267166",
  },
  {
    id: 5,
    task: "Start your day with a gratitude practice",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg13.jpg?alt=media&token=436b7bac-b3bd-4d45-93e6-d7c912c477c6",
  },
  {
    id: 6,
    task: "Engage in some Creative Activity",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg14.jpg?alt=media&token=79108674-0fd4-4cc2-b66e-db9184a82958",
  },
  {
    id: 7,
    task: "Listen to a motivational podcast ",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg15.png?alt=media&token=e7b0da46-a47c-4705-9cb7-09ef327e413f",
  },
  // ***** AFTERNOON *****
  {
    id: 8,
    task: "Take short breaks between study sessions",
    complete: false,
    time: "afternoon",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg16.jpg?alt=media&token=ee25a116-a60b-4c2b-b2e3-bd2296f730f5",
  },
  {
    id: 9,
    task: "Eat a balanced lunch ",
    complete: false,
    time: "afternoon",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg17.jpg?alt=media&token=92b92e46-f982-4dbb-9187-f5d2941c23aa",
  },
  {
    id: 10,
    task: "Engage in mindfulness exercises",
    complete: false,
    time: "afternoon",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg18.jpg?alt=media&token=fbcb579e-7d99-4686-b423-df94757dc654",
  },
  // ***** NIGHT *****
  {
    id: 11,
    task: "Finish your academic work and assignments",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg19.jpg?alt=media&token=5a8650d0-4f5b-4b1f-884e-0336e93c52c5",
  },
  {
    id: 12,
    task: "Limit screen time before bedtime",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg2.jpg?alt=media&token=3549d878-6e92-49d0-9bbc-b8e5759c69f6",
  },
  {
    id: 13,
    task: "Practice reading a book",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg20.jpg?alt=media&token=ec67f97c-74a8-4c4a-9820-86b578bc3d06",
  },
  {
    id: 14,
    task: "Reflect on your day",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg21.jpg?alt=media&token=4ed07d22-59ae-41c3-a474-7b51e282a11d",
  },
  {
    id: 15,
    task: "Plan for the next day",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg22.jpg?alt=media&token=5f44bb77-4313-4578-ad67-8ad582365572",
  },
  {
    id: 16,
    task: "Connect with friends or family",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg23.png?alt=media&token=66c3564f-948c-4390-92aa-a2f37caab5cd",
  },
];
export const workingProfessionalRoutine = [
  // ***** MORNING *****
  {
    id: 1,
    task: "Have a nutritious breakfast",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg24.jpg?alt=media&token=36c8b228-c1a0-4d7a-9da2-11f45399918d",
  },
  {
    id: 2,
    task: "Engage in some light physical activity",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg25.jpg?alt=media&token=1f1c02a9-41e0-4c6c-9497-2e1cdf267166",
  },
  {
    id: 3,
    task: "Review your goals for the day",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg27.jpg?alt=media&token=0fe1a8fc-676b-42c5-8b42-ee62b80d81a7",
  },
  {
    id: 4,
    task: "Practice affirmations or positive self-talk",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg26.jpg?alt=media&token=a46ab49f-1659-42cc-abef-81e7d90e6051",
  },
  {
    id: 5,
    task: "Practice gratitude",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg28.jpg?alt=media&token=27b61808-808d-4c55-b0d2-bbe87ba3c2ec",
  },
  // ***** AFTERNOON *****
  {
    id: 6,
    task: "Have a balanced and healthy lunch",
    complete: false,
    time: "afternoon",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg29.jpg?alt=media&token=f2807f55-641b-4bfe-b2e0-d2a1673ba356",
  },
  {
    id: 7,
    task: "Practice deep breathing exercises",
    complete: false,
    time: "afternoon",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg3.jpg?alt=media&token=adda66fc-fe62-4712-a3b6-27a645aacf98",
  },
  {
    id: 8,
    task: "Take short breaks to stand up, stretch, or walk around",
    complete: false,
    time: "afternoon",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg30.jpg?alt=media&token=21d4d74b-d3a2-4af5-ba14-548551e2042e",
  },
  // ***** NIGHT *****
  {
    id: 9,
    task: "Read a book",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg4.jpg?alt=media&token=7ceb02a6-52d6-4f4f-96d2-f439c1f4ed34",
  },
  {
    id: 10,
    task: "Create a bedtime ritual, like reducing screen time",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg5.jpg?alt=media&token=83100e42-f610-454a-99e4-efec6173de19",
  },
  {
    id: 11,
    task: "Reflect on the day in a journal",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg6.jpg?alt=media&token=d81af21a-e95b-4ec4-95b4-25cb3775693f",
  },
  {
    id: 12,
    task: "Take a Night Walk",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg7.jpg?alt=media&token=7f084a1a-c801-483e-84c8-d63ac70b899f",
  },
  {
    id: 13,
    task: "Connect with Family and Friends",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg8.jpg?alt=media&token=fee4c377-a5ae-41ec-b98f-020acd4ccb78",
  },
];
export const houseWifeRoutine = [
  // ***** MORNING *****
  {
    id: 1,
    task: "Wake up early",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg9.jpg?alt=media&token=fb7ff0ea-93c8-4f96-9fbd-0d8a533cf0a4",
  },
  {
    id: 2,
    task: "Stretch or exercise",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg1.jpg?alt=media&token=d3cfed58-378d-4d15-afa8-2bc13d2f1093",
  },
  {
    id: 3,
    task: "Meditate or practice mindfulness",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg10.jpg?alt=media&token=df13fa1f-83be-4d57-9654-38a103361f71",
  },
  {
    id: 4,
    task: "Eat a nutritious breakfast",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg11.jpg?alt=media&token=736d6a5b-2a95-4504-b013-7c1581dce281",
  },
  {
    id: 5,
    task: "Practice gratitude",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg12.jpg?alt=media&token=7b6d3049-f5bc-45fe-bd36-cd9ae88b9640",
  },
  // ***** AFTERNOON *****
  {
    id: 6,
    task: "Practice mindfulness or deep breathing",
    complete: false,
    time: "afternoon",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg13.jpg?alt=media&token=436b7bac-b3bd-4d45-93e6-d7c912c477c6",
  },
  {
    id: 7,
    task: "Engage in a hobby or leisure activity",
    complete: false,
    time: "afternoon",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg14.jpg?alt=media&token=79108674-0fd4-4cc2-b66e-db9184a82958",
  },
  {
    id: 8,
    task: "Connect with people",
    complete: false,
    time: "afternoon",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg15.png?alt=media&token=e7b0da46-a47c-4705-9cb7-09ef327e413f",
  },
  // ***** NIGHT *****
  {
    id: 9,
    task: "Connect with nature",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg16.jpg?alt=media&token=ee25a116-a60b-4c2b-b2e3-bd2296f730f5",
  },
  {
    id: 10,
    task: "Plan your day",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg17.jpg?alt=media&token=92b92e46-f982-4dbb-9187-f5d2941c23aa",
  },
  {
    id: 11,
    task: "Disconnect from screens",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg18.jpg?alt=media&token=fbcb579e-7d99-4686-b423-df94757dc654",
  },
  {
    id: 12,
    task: "Reflect on the day",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg19.jpg?alt=media&token=5a8650d0-4f5b-4b1f-884e-0336e93c52c5",
  },
];
export const oldAgeRoutine = [
  // ***** MORNING *****
  {
    id: 1,
    task: "Wake up at a consistent time",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg2.jpg?alt=media&token=3549d878-6e92-49d0-9bbc-b8e5759c69f6",
  },
  {
    id: 2,
    task: "Have a nutritious breakfast",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg20.jpg?alt=media&token=ec67f97c-74a8-4c4a-9820-86b578bc3d06",
  },
  {
    id: 3,
    task: "Engage in light mental exercises",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg21.jpg?alt=media&token=4ed07d22-59ae-41c3-a474-7b51e282a11d",
  },
  {
    id: 4,
    task: "Start with gentle stretches or yoga ",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg22.jpg?alt=media&token=5f44bb77-4313-4578-ad67-8ad582365572",
  },
  {
    id: 5,
    task: "Playing with GrandChildren",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg23.png?alt=media&token=66c3564f-948c-4390-92aa-a2f37caab5cd",
  },
  {
    id: 6,
    task: "Participate in social activities, like joining a senior center",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg24.jpg?alt=media&token=36c8b228-c1a0-4d7a-9da2-11f45399918d",
  },
  {
    id: 7,
    task: "Read Newspaper",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg25.jpg?alt=media&token=1f1c02a9-41e0-4c6c-9497-2e1cdf267166",
  },
  // ***** AFTERNOON *****
  {
    id: 8,
    task: "Participate in hobbies or activities that the person enjoys, such as painting, gardening, or playing a musical instrument.",
    complete: false,
    time: "afternoon",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg26.jpg?alt=media&token=a46ab49f-1659-42cc-abef-81e7d90e6051",
  },
  {
    id: 9,
    task: "Spend time doing light household chores",
    complete: false,
    time: "afternoon",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg27.jpg?alt=media&token=0fe1a8fc-676b-42c5-8b42-ee62b80d81a7",
  },
  {
    id: 10,
    task: "Engage in low-impact exercises like chair yoga",
    complete: false,
    time: "afternoon",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg28.jpg?alt=media&token=27b61808-808d-4c55-b0d2-bbe87ba3c2ec",
  },
  // ***** NIGHT *****
  {
    id: 11,
    task: "Read books, magazines, or articles on subjects of interest",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg29.jpg?alt=media&token=f2807f55-641b-4bfe-b2e0-d2a1673ba356",
  },
  {
    id: 12,
    task: "Take a Walk",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg3.jpg?alt=media&token=adda66fc-fe62-4712-a3b6-27a645aacf98",
  },
  {
    id: 13,
    task: "Socialize with friends or family",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg30.jpg?alt=media&token=21d4d74b-d3a2-4af5-ba14-548551e2042e",
  },
  {
    id: 14,
    task: "Practice mindfulness or meditation",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg4.jpg?alt=media&token=7ceb02a6-52d6-4f4f-96d2-f439c1f4ed34",
  },
  {
    id: 15,
    task: "Watch a lighthearted movie or listen to soothing music",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg5.jpg?alt=media&token=83100e42-f610-454a-99e4-efec6173de19",
  },
  {
    id: 16,
    task: "Spend quality time with loved ones",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg6.jpg?alt=media&token=d81af21a-e95b-4ec4-95b4-25cb3775693f",
  },
];
export const yourWay = [
  {
    id: 1,
    task: "Add Your Morning Task Here",
    complete: false,
    time: "morning",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg7.jpg?alt=media&token=7f084a1a-c801-483e-84c8-d63ac70b899f",
  },
  {
    id: 2,
    task: "Add Your Afternoon Task Here",
    complete: false,
    time: "afternoon",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg8.jpg?alt=media&token=fee4c377-a5ae-41ec-b98f-020acd4ccb78",
  },
  {
    id: 3,
    task: "Add Your Night Task Here",
    complete: false,
    time: "night",
    img: "https://firebasestorage.googleapis.com/v0/b/reflect-manas.appspot.com/o/home%2Ficon%2FtaskImg9.jpg?alt=media&token=fb7ff0ea-93c8-4f96-9fbd-0d8a533cf0a4",
  },
];
