export const studentRoutine = [
  // ***** MORNING *****
  {
    id: 1,
    task: "Wake up early",
    complete: false,
    time: "morning",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/zacp0rqiezkrnlrdvac4.jpg",
  },
  {
    id: 2,
    task: "Have a healthy breakfast",
    complete: false,
    time: "morning",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547558/home-icons/kcg5so9173r3luyjfwba.jpg",
  },
  {
    id: 3,
    task: "Spend some time in nature",
    complete: false,
    time: "morning",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547558/home-icons/mjfusq7ac5dsehsfxzax.jpg",
  },
  {
    id: 4,
    task: "Start your day with a gratitude practice",
    complete: false,
    time: "morning",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547558/home-icons/dldguyu857r2qzrtthwr.jpg",
  },
  {
    id: 5,
    task: "Engage in some Creative Activity",
    complete: false,
    time: "morning",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547558/home-icons/p3dwwnoexqctzgelxd1u.jpg",
  },
  {
    id: 6,
    task: "Listen to a motivational podcast ",
    complete: false,
    time: "morning",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547558/home-icons/s1f8uuo9uwlxsze9r59h.jpg",
  },
  // ***** AFTERNOON *****
  {
    id: 7,
    task: "Take short breaks between study sessions",
    complete: false,
    time: "afternoon",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547558/home-icons/pn2vvac4flfksizo0ewy.jpg",
  },
  {
    id: 8,
    task: "Eat a balanced lunch ",
    complete: false,
    time: "afternoon",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547558/home-icons/mfpmqaglummafpyhjwnm.jpg",
  },
  // ***** NIGHT *****
  {
    id: 9,
    task: "Finish your academic work and assignments",
    complete: false,
    time: "night",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547558/home-icons/rx3omietndfhspeld6im.jpg",
  },
  {
    id: 10,
    task: "Limit screen time before bedtime",
    complete: false,
    time: "night",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547558/home-icons/ovehfm5vy62eum8dbquo.jpg",
  },
  {
    id: 11,
    task: "Practice reading a book",
    complete: false,
    time: "night",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547558/home-icons/owppsnnvkhvrazk2tvwl.jpg",
  },
  {
    id: 12,
    task: "Plan for the next day",
    complete: false,
    time: "night",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547558/home-icons/tpxi2fybc4pobcdxw5cg.jpg",
  },
  {
    id: 13,
    task: "Connect with friends or family",
    complete: false,
    time: "night",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547560/home-icons/swnodkxmx9hljsc1kx5y.jpg",
  },
  // ***** MUST DO *****
  {
    id: 14,
    task: "Stretch and do some Physical Exercise",
    complete: false,
    time: "must-do",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/kffwwnplklt94erbarqd.jpg",
  },
  {
    id: 15,
    task: "Practice Deep Breathing",
    complete: false,
    time: "must-do",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/xfwjgqk6ogtuvmrhgmrm.jpg",
  },
  {
    id: 16,
    task: "Engage in Meditation Activities",
    complete: false,
    time: "must-do",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/yq35v5wi2evrhqlpound.png",
  },
  {
    id: 17,
    task: "Reflect on the day in a Journal",
    complete: false,
    time: "must-do",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/sggebry7msmmydssglte.jpg",
  },
];
export const workingProfessionalRoutine = [
  // ***** MORNING *****
  {
    id: 1,
    task: "Have a nutritious breakfast",
    complete: false,
    time: "morning",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547560/home-icons/spzux4yzrq6qnshqrlc8.jpg",
  },
  {
    id: 2,
    task: "Review your goals for the day",
    complete: false,
    time: "morning",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547560/home-icons/rsofjky9pjqo41xmrtte.jpg",
  },
  {
    id: 3,
    task: "Practice affirmations or positive self-talk",
    complete: false,
    time: "morning",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547560/home-icons/z3arafwl8vwbkghvnjop.jpg",
  },
  {
    id: 4,
    task: "Practice gratitude",
    complete: false,
    time: "morning",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547560/home-icons/pqb6i2x7qrjkbm09nq1s.jpg",
  },
  {
    id: 5,
    task: "Have a balanced and healthy lunch",
    complete: false,
    time: "afternoon",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547560/home-icons/llq9zrqezt9c2acxczhf.jpg",
  },
  {
    id: 6,
    task: "Take short breaks to stand up, stretch, or walk around",
    complete: false,
    time: "afternoon",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547560/home-icons/fj1mwamrl1d3ethfzdst.jpg",
  },
  // ***** NIGHT *****
  {
    id: 7,
    task: "Read a book",
    complete: false,
    time: "night",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547560/home-icons/ld67iai7vnktvyn7yrgg.png",
  },
  {
    id: 8,
    task: "Create a bedtime ritual, like reducing screen time",
    complete: false,
    time: "night",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547560/home-icons/drgb6rfk9busqia5k6jo.jpg",
  },
  {
    id: 9,
    task: "Take a Night Walk",
    complete: false,
    time: "night",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/wyhf7l93ruxktwmzaxhi.jpg",
  },
  {
    id: 10,
    task: "Connect with Family and Friends",
    complete: false,
    time: "night",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/ep6gkxbfjhand1cekzrv.jpg",
  },
  // ***** MUST DO *****
  {
    id: 11,
    task: "Stretch and do some Physical Exercise",
    complete: false,
    time: "must-do",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/kffwwnplklt94erbarqd.jpg",
  },
  {
    id: 12,
    task: "Practice Deep Breathing",
    complete: false,
    time: "must-do",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/xfwjgqk6ogtuvmrhgmrm.jpg",
  },
  {
    id: 13,
    task: "Engage in Meditation Activities",
    complete: false,
    time: "must-do",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/yq35v5wi2evrhqlpound.png",
  },
  {
    id: 14,
    task: "Reflect on the day in a Journal",
    complete: false,
    time: "must-do",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/sggebry7msmmydssglte.jpg",
  },
];
export const houseWifeRoutine = [
  // ***** MORNING *****
  {
    id: 1,
    task: "Wake up early",
    complete: false,
    time: "morning",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/ep6gkxbfjhand1cekzrv.jpg",
  },
  {
    id: 2,
    task: "Eat a nutritious breakfast",
    complete: false,
    time: "morning",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/o9jxdvi6mmxawnjhxlws.jpg",
  },
  {
    id: 3,
    task: "Practice gratitude",
    complete: false,
    time: "morning",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/cicqdiyqd0xszpkzfsjg.jpg",
  },
  // ***** AFTERNOON *****
  {
    id: 4,
    task: "Engage in a hobby or leisure activity",
    complete: false,
    time: "afternoon",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/yq35v5wi2evrhqlpound.png",
  },
  {
    id: 5,
    task: "Connect with people",
    complete: false,
    time: "afternoon",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/sggebry7msmmydssglte.jpg",
  },
  // ***** NIGHT *****
  {
    id: 6,
    task: "Connect with nature",
    complete: false,
    time: "night",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/ljvcwh4bldcvhcmqhhib.jpg",
  },
  {
    id: 7,
    task: "Plan your day",
    complete: false,
    time: "night",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/xfwjgqk6ogtuvmrhgmrm.jpg",
  },
  {
    id: 8,
    task: "Disconnect from screens",
    complete: false,
    time: "night",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/zacp0rqiezkrnlrdvac4.jpg",
  },
  // ***** MUST DO *****
  {
    id: 9,
    task: "Stretch and do some Physical Exercise",
    complete: false,
    time: "must-do",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/kffwwnplklt94erbarqd.jpg",
  },
  {
    id: 10,
    task: "Practice Deep Breathing",
    complete: false,
    time: "must-do",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/xfwjgqk6ogtuvmrhgmrm.jpg",
  },
  {
    id: 11,
    task: "Engage in Meditation Activities",
    complete: false,
    time: "must-do",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/yq35v5wi2evrhqlpound.png",
  },
  {
    id: 12,
    task: "Reflect on the day in a Journal",
    complete: false,
    time: "must-do",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/sggebry7msmmydssglte.jpg",
  },
];
export const oldAgeRoutine = [
  // ***** MORNING *****
  {
    id: 1,
    task: "Wake up at a consistent time",
    complete: false,
    time: "morning",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547558/home-icons/kcg5so9173r3luyjfwba.jpg",
  },
  {
    id: 2,
    task: "Have a nutritious breakfast",
    complete: false,
    time: "morning",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547558/home-icons/mjfusq7ac5dsehsfxzax.jpg",
  },
  {
    id: 3,
    task: "Playing with GrandChildren",
    complete: false,
    time: "morning",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547558/home-icons/p3dwwnoexqctzgelxd1u.jpg",
  },
  {
    id: 4,
    task: "Participate in social activities, like joining a senior center",
    complete: false,
    time: "morning",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547558/home-icons/pn2vvac4flfksizo0ewy.jpg",
  },
  {
    id: 5,
    task: "Read Newspaper",
    complete: false,
    time: "morning",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547558/home-icons/rx3omietndfhspeld6im.jpg",
  },
  // ***** AFTERNOON *****
  {
    id: 6,
    task: "Participate in hobbies or activities that the person enjoys, such as painting, gardening.",
    complete: false,
    time: "afternoon",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547558/home-icons/owppsnnvkhvrazk2tvwl.jpg",
  },
  {
    id: 7,
    task: "Spend time doing light household chores",
    complete: false,
    time: "afternoon",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547560/home-icons/swnodkxmx9hljsc1kx5y.jpg",
  },
  // ***** NIGHT *****
  {
    id: 8,
    task: "Read books, magazines, or articles on subjects of interest",
    complete: false,
    time: "night",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547560/home-icons/rsofjky9pjqo41xmrtte.jpg",
  },
  {
    id: 9,
    task: "Take a Walk",
    complete: false,
    time: "night",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547560/home-icons/pqb6i2x7qrjkbm09nq1s.jpg",
  },
  {
    id: 10,
    task: "Socialize with friends or family",
    complete: false,
    time: "night",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547560/home-icons/fj1mwamrl1d3ethfzdst.jpg",
  },
  {
    id: 11,
    task: "Watch a lighthearted movie or listen to soothing music",
    complete: false,
    time: "night",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547560/home-icons/drgb6rfk9busqia5k6jo.jpg",
  },
  {
    id: 12,
    task: "Spend quality time with loved ones",
    complete: false,
    time: "night",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/ep6gkxbfjhand1cekzrv.jpg",
  },
  // ***** MUST DO *****
  {
    id: 13,
    task: "Stretch and do some Physical Exercise",
    complete: false,
    time: "must-do",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/kffwwnplklt94erbarqd.jpg",
  },
  {
    id: 14,
    task: "Practice Deep Breathing",
    complete: false,
    time: "must-do",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/xfwjgqk6ogtuvmrhgmrm.jpg",
  },
  {
    id: 15,
    task: "Engage in Meditation Activities",
    complete: false,
    time: "must-do",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/yq35v5wi2evrhqlpound.png",
  },
  {
    id: 16,
    task: "Reflect on the day in a Journal",
    complete: false,
    time: "must-do",
    img: "https://res.cloudinary.com/di9xrtfcu/image/upload/v1706547559/home-icons/sggebry7msmmydssglte.jpg",
  },
];
